name: ci
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  eslint-test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
      - name: CI, Linter, Test with Coverage and Build
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          TESTING_NODE_ENV: ${{ secrets.TESTING_NODE_ENV }}
          TESTING_DB_HOST: ${{ secrets.TESTING_DB_HOST }}
          TESTING_DB_PORT_NUMBER: ${{ secrets.TESTING_DB_PORT_NUMBER }}
          TESTING_DB_NAME: ${{ secrets.TESTING_DB_NAME }}
          TESTING_DB_USERNAME: ${{ secrets.TESTING_DB_USERNAME }}
          TESTING_DB_PASSWORD: ${{ secrets.TESTING_DB_PASSWORD }}
        run: |
          npm ci --legacy-peer-deps
          npm run lint
          npm run test:e2e
          npm run test:cov
          npm run build
