name: ci
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  eslint-test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
      - name: CI, Linter, Test with Coverage and Build
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          npm ci --legacy-peer-deps
          npm run lint
          npm run test:e2e
          npm run test:cov
          npm run build
