name: cov
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  upload-coverage-report:
    runs-on: ${{ matrix.os }}
    permissions:
      actions: read
      contents: write
      security-events: write
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node-version: [16.x, 17.x, 18.x, 19.x, 20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Test with Coverage
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          npm ci --legacy-peer-deps
          npm run test:cov
      - name: Upload Coverage Report to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/clover.xml,coverage/coverage-final.json,coverage/lcov.info
          fail_ci_if_error: true
          flags: unit_test
          name: OpenriceCanadaBackend
          verbose: true
